In [20]:
import pandas as pd
import numpy as np

s= pd.Series([4,5,np.nan,23,])
s

0     4.0
1     5.0
2     NaN
3    23.0
dtype: float64

In [21]:
df=pd.DataFrame({'temperature':s,'humidity':np.random.randn(4)})

In [22]:
df

   temperature  humidity
0          4.0  0.381528
1          5.0 -1.921917
2          NaN  1.274573
3         23.0 -0.255719

In [24]:
import pandas as pd
hospitalsFile = "../../data/health-valais/hospitals.csv"

hospitals=pd.read_csv(hospitalsFile,encoding='utf-8')

hospitals

,CLASSE,ETABLISSEMENT,Adresse,numero,npa,ville,telephone,site_internet,RuleID,RuleID_1,RuleID_2,beds
0,1,HVS - Hôpital psychiatrique de Malévoz,Route de Morgins,10.0,1870,Monthey,0800 012 210,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,30
1,1,HVS - Clinique de Saint-Amé,Vers Saint-Amé,10.0,1890,St-Maurice,027/604.66.55,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,20
2,1,HVS - Hôpital de Martigny,Avenue de la Fusion,27.0,1920,Martigny,027/603.90.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,10
3,1,HVS - Hôpital de Sion,Avenue du Grand-Champsec,80.0,1951,Sion,027/603.40.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,11
4,1,HVS - Institut Central des Hôpitaux ICH,Avenue du Grand-Champsec,86.0,1951,Sion,027/603.47.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,15
5,1,HVS - Hôpital de Sierre,Rue St-Charles,14.0,3960,Sierre,027/603.70.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,30
6,1,HVS - Centre Valaisan de Pneumologie (CVP),Route de la Moubra,87.0,3963,Crans-Montana,027/603.80.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,12
7,1,HVS - Hôpital de Brigue,Oberlandstrasse,14.0,3900,Brig,027/604.33.33,http://www.spitalvs.ch/de/spital-wallis/stando...,NaN,Rule_1,Rule_1,45
8,1,HVS - Hôpital de Vige,Pflanzettastrasse,8.0,3930,Visp,027/604.33.33,http://www.spitalvs.ch/de/spital-wallis/stando...,NaN,Rule_1,Rule_1,23
9,1,HRC - Hôpital de Monthey,Route de Morgins,54.0,1870,Monthey,024/473.17.31,http://www.hopitalrivierachablais.ch,NaN,Rule_1,Rule_1,45
10,1,HRC - Hôpital d'Aigle,Chemin du Grand-Chne,NaN,1860,Aigle,024/468.86.88,http://www.hopitalrivierachablais.ch,NaN,Rule_1,Rule_1,23
11,1,HRC - Hôpital de Vevey la Providence,Av. de la Prairie,3.0,1800,Vevey,021/977.55.55,http://www.hopitalrivierachablais.ch,NaN,Rule_1,Rule_1,34
12,1,Clinique de Valre,Rue Pré-Fleuri,16.0,1950,Sion,027/327.10.10,http://www.cliniquevalere.ch,NaN,Rule_1,Rule_1,12
13,1,Clinique CIC Valais,Route du Léman,29.0,1907,Saxon,027/743.40.40,http://www.cic-valais.ch,NaN,Rule_1,Rule_1,43
14,1,Leukerbad Clinic,Willy-Spühlerstrasse,2.0,3954,Leukerbad,027/472.51.08,http://www.leukerbadclinic.ch,NaN,Rule_1,Rule_1,33
15,1,Berner Klinik Montana,Impasse Palace Bellevue,1.0,3963,Crans-Montana,027/485.51.21,http://www.bernerklinik.ch,NaN,Rule_1,Rule_1,44
16,1,Luzerner Höhenklinik Montana,Rte de L'Astoria,2.0,3963,Crans-Montana,027/485.81.81,http://www.lhm.ch,NaN,Rule_1,Rule_1,22
17,1,Clinique romande de réadaptation (CRR SUVA),Avenue Grand-Champsec,90.0,1951,Sion,027/603.30.30,http://www.crr-suva.ch,NaN,Rule_1,Rule_1,33
18,1,HRC - Hôpital de Vevey le Samaritain,Boulevard Paderewski,3.0,1800,Vevey,021/923.40.00,http://www.hopitalrivierachablais.ch,NaN,Rule_1,Rule_1,50
19,1,HRC - Hôpital de Montreux,Avenue de Belmont,25.0,1820,Montreuy,021/966.66.66,http://www.hopitalrivierachablais.ch,NaN,Rule_1,Rule_1,33
20,1,HVS - Psychiatriezentrum Oberwallis,Oberlandstrasse,14.0,3900,Brig,027/604.33.33,http://www.hopitalvs.ch/de/unsere-fachbereiche...,NaN,Rule_1,Rule_1,42
21,1,HUG-Clinique de Crans-Montana,Impasse Clairmont,2.0,3963,Crans-Montana,027/485.61.11,http://www.hug-ge.ch/crans-montana,NaN,Rule_1,Rule_1,22

In [25]:
hospitals.head(3)

,CLASSE,ETABLISSEMENT,Adresse,numero,npa,ville,telephone,site_internet,RuleID,RuleID_1,RuleID_2,beds
0,1,HVS - Hôpital psychiatrique de Malévoz,Route de Morgins,10.0,1870,Monthey,0800 012 210,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,30
1,1,HVS - Clinique de Saint-Amé,Vers Saint-Amé,10.0,1890,St-Maurice,027/604.66.55,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,20
2,1,HVS - Hôpital de Martigny,Avenue de la Fusion,27.0,1920,Martigny,027/603.90.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,10

In [26]:
hospitals.columns

Index(['CLASSE', 'ETABLISSEMENT', 'Adresse', 'numero', 'npa', 'ville',
       'telephone', 'site_internet', 'RuleID', 'RuleID_1', 'RuleID_2', 'beds'],
      dtype='object')

In [27]:
hospitals.index

RangeIndex(start=0, stop=22, step=1)

In [28]:
len(hospitals)

22

In [29]:
hospitals.shape

(22, 12)

In [30]:
hospitals.dtypes

CLASSE             int64
ETABLISSEMENT     object
Adresse           object
numero           float64
npa                int64
ville             object
telephone         object
site_internet     object
RuleID           float64
RuleID_1          object
RuleID_2          object
beds               int64
dtype: object

In [31]:
hospitals['Adresse']

0             Route de Morgins
1               Vers Saint-Amé
2          Avenue de la Fusion
3     Avenue du Grand-Champsec
4     Avenue du Grand-Champsec
5               Rue St-Charles
6           Route de la Moubra
7              Oberlandstrasse
8            Pflanzettastrasse
9             Route de Morgins
10       Chemin du Grand-Chne
11           Av. de la Prairie
12              Rue Pré-Fleuri
13              Route du Léman
14        Willy-Spühlerstrasse
15     Impasse Palace Bellevue
16            Rte de L'Astoria
17       Avenue Grand-Champsec
18        Boulevard Paderewski
19           Avenue de Belmont
20             Oberlandstrasse
21           Impasse Clairmont
Name: Adresse, dtype: object

In [32]:
hospitals['beds'].mean()

28.727272727272727

In [33]:
hospitals['beds'].max()

50

In [34]:
hospitals.describe()

       CLASSE     numero          npa  RuleID       beds
count    22.0  21.000000    22.000000     0.0  22.000000
mean      1.0  27.476190  2728.909091     NaN  28.727273
std       0.0  31.512885  1035.833178     NaN  12.585637
min       1.0   1.000000  1800.000000     NaN  10.000000
25%       1.0   3.000000  1875.000000     NaN  20.500000
50%       1.0  14.000000  1951.000000     NaN  30.000000
75%       1.0  29.000000  3948.000000     NaN  40.000000
max       1.0  90.000000  3963.000000     NaN  50.000000

In [35]:
aList=[4,6,2,1,6]
aSeries=pd.Series(aList)
aSeries

0    4
1    6
2    2
3    1
4    6
dtype: int64

In [36]:
aDataFrame=pd.DataFrame(aSeries)
aDataFrame.columns=["colName"]
aDataFrame

   colName
0        4
1        6
2        2
3        1
4        6

In [37]:
hospitals['newBeds']=0
hospitals

,CLASSE,ETABLISSEMENT,Adresse,numero,npa,ville,telephone,site_internet,RuleID,RuleID_1,RuleID_2,beds,newBeds
0,1,HVS - Hôpital psychiatrique de Malévoz,Route de Morgins,10.0,1870,Monthey,0800 012 210,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,30,0
1,1,HVS - Clinique de Saint-Amé,Vers Saint-Amé,10.0,1890,St-Maurice,027/604.66.55,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,20,0
2,1,HVS - Hôpital de Martigny,Avenue de la Fusion,27.0,1920,Martigny,027/603.90.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,10,0
3,1,HVS - Hôpital de Sion,Avenue du Grand-Champsec,80.0,1951,Sion,027/603.40.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,11,0
4,1,HVS - Institut Central des Hôpitaux ICH,Avenue du Grand-Champsec,86.0,1951,Sion,027/603.47.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,15,0
5,1,HVS - Hôpital de Sierre,Rue St-Charles,14.0,3960,Sierre,027/603.70.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,30,0
6,1,HVS - Centre Valaisan de Pneumologie (CVP),Route de la Moubra,87.0,3963,Crans-Montana,027/603.80.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,12,0
7,1,HVS - Hôpital de Brigue,Oberlandstrasse,14.0,3900,Brig,027/604.33.33,http://www.spitalvs.ch/de/spital-wallis/stando...,NaN,Rule_1,Rule_1,45,0
8,1,HVS - Hôpital de Vige,Pflanzettastrasse,8.0,3930,Visp,027/604.33.33,http://www.spitalvs.ch/de/spital-wallis/stando...,NaN,Rule_1,Rule_1,23,0
9,1,HRC - Hôpital de Monthey,Route de Morgins,54.0,1870,Monthey,024/473.17.31,http://www.hopitalrivierachablais.ch,NaN,Rule_1,Rule_1,45,0
10,1,HRC - Hôpital d'Aigle,Chemin du Grand-Chne,NaN,1860,Aigle,024/468.86.88,http://www.hopitalrivierachablais.ch,NaN,Rule_1,Rule_1,23,0
11,1,HRC - Hôpital de Vevey la Providence,Av. de la Prairie,3.0,1800,Vevey,021/977.55.55,http://www.hopitalrivierachablais.ch,NaN,Rule_1,Rule_1,34,0
12,1,Clinique de Valre,Rue Pré-Fleuri,16.0,1950,Sion,027/327.10.10,http://www.cliniquevalere.ch,NaN,Rule_1,Rule_1,12,0
13,1,Clinique CIC Valais,Route du Léman,29.0,1907,Saxon,027/743.40.40,http://www.cic-valais.ch,NaN,Rule_1,Rule_1,43,0
14,1,Leukerbad Clinic,Willy-Spühlerstrasse,2.0,3954,Leukerbad,027/472.51.08,http://www.leukerbadclinic.ch,NaN,Rule_1,Rule_1,33,0
15,1,Berner Klinik Montana,Impasse Palace Bellevue,1.0,3963,Crans-Montana,027/485.51.21,http://www.bernerklinik.ch,NaN,Rule_1,Rule_1,44,0
16,1,Luzerner Höhenklinik Montana,Rte de L'Astoria,2.0,3963,Crans-Montana,027/485.81.81,http://www.lhm.ch,NaN,Rule_1,Rule_1,22,0
17,1,Clinique romande de réadaptation (CRR SUVA),Avenue Grand-Champsec,90.0,1951,Sion,027/603.30.30,http://www.crr-suva.ch,NaN,Rule_1,Rule_1,33,0
18,1,HRC - Hôpital de Vevey le Samaritain,Boulevard Paderewski,3.0,1800,Vevey,021/923.40.00,http://www.hopitalrivierachablais.ch,NaN,Rule_1,Rule_1,50,0
19,1,HRC - Hôpital de Montreux,Avenue de Belmont,25.0,1820,Montreuy,021/966.66.66,http://www.hopitalrivierachablais.ch,NaN,Rule_1,Rule_1,33,0
20,1,HVS - Psychiatriezentrum Oberwallis,Oberlandstrasse,14.0,3900,Brig,027/604.33.33,http://www.hopitalvs.ch/de/unsere-fachbereiche...,NaN,Rule_1,Rule_1,42,0
21,1,HUG-Clinique de Crans-Montana,Impasse Clairmont,2.0,3963,Crans-Montana,027/485.61.11,http://www.hug-ge.ch/crans-montana,NaN,Rule_1,Rule_1,22,0

In [38]:
hospitals['newBeds']=hospitals['beds']*2
hospitals.head()

,CLASSE,ETABLISSEMENT,Adresse,numero,npa,ville,telephone,site_internet,RuleID,RuleID_1,RuleID_2,beds,newBeds
0,1,HVS - Hôpital psychiatrique de Malévoz,Route de Morgins,10.0,1870,Monthey,0800 012 210,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,30,60
1,1,HVS - Clinique de Saint-Amé,Vers Saint-Amé,10.0,1890,St-Maurice,027/604.66.55,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,20,40
2,1,HVS - Hôpital de Martigny,Avenue de la Fusion,27.0,1920,Martigny,027/603.90.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,10,20
3,1,HVS - Hôpital de Sion,Avenue du Grand-Champsec,80.0,1951,Sion,027/603.40.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,11,22
4,1,HVS - Institut Central des Hôpitaux ICH,Avenue du Grand-Champsec,86.0,1951,Sion,027/603.47.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,15,30

In [39]:
hospitals[5:8]

,CLASSE,ETABLISSEMENT,Adresse,numero,npa,ville,telephone,site_internet,RuleID,RuleID_1,RuleID_2,beds,newBeds
5,1,HVS - Hôpital de Sierre,Rue St-Charles,14.0,3960,Sierre,027/603.70.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,30,60
6,1,HVS - Centre Valaisan de Pneumologie (CVP),Route de la Moubra,87.0,3963,Crans-Montana,027/603.80.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,12,24
7,1,HVS - Hôpital de Brigue,Oberlandstrasse,14.0,3900,Brig,027/604.33.33,http://www.spitalvs.ch/de/spital-wallis/stando...,NaN,Rule_1,Rule_1,45,90

In [40]:
hospitals.loc[11]

CLASSE                                              1
ETABLISSEMENT    HRC - Hôpital de Vevey la Providence
Adresse                             Av. de la Prairie
numero                                              3
npa                                              1800
ville                                           Vevey
telephone                               021/977.55.55
site_internet    http://www.hopitalrivierachablais.ch
RuleID                                            NaN
RuleID_1                                       Rule_1
RuleID_2                                       Rule_1
beds                                               34
newBeds                                            68
Name: 11, dtype: object

In [41]:
hospitals.loc[9:12, ['ETABLISSEMENT','beds']]

                           ETABLISSEMENT  beds
9               HRC - Hôpital de Monthey    45
10                 HRC - Hôpital d'Aigle    23
11  HRC - Hôpital de Vevey la Providence    34
12                    Clinique de Valre    12

In [42]:
hospitals.loc[(hospitals['Adresse'].str.startswith('Avenue')) & (hospitals['beds']<15)]

,CLASSE,ETABLISSEMENT,Adresse,numero,npa,ville,telephone,site_internet,RuleID,RuleID_1,RuleID_2,beds,newBeds
2,1,HVS - Hôpital de Martigny,Avenue de la Fusion,27.0,1920,Martigny,027/603.90.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,10,20
3,1,HVS - Hôpital de Sion,Avenue du Grand-Champsec,80.0,1951,Sion,027/603.40.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,11,22

In [43]:
hospitals.sort_values(by='npa',ascending=False).head()

,CLASSE,ETABLISSEMENT,Adresse,numero,npa,ville,telephone,site_internet,RuleID,RuleID_1,RuleID_2,beds,newBeds
21,1,HUG-Clinique de Crans-Montana,Impasse Clairmont,2.0,3963,Crans-Montana,027/485.61.11,http://www.hug-ge.ch/crans-montana,NaN,Rule_1,Rule_1,22,44
16,1,Luzerner Höhenklinik Montana,Rte de L'Astoria,2.0,3963,Crans-Montana,027/485.81.81,http://www.lhm.ch,NaN,Rule_1,Rule_1,22,44
6,1,HVS - Centre Valaisan de Pneumologie (CVP),Route de la Moubra,87.0,3963,Crans-Montana,027/603.80.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,12,24
15,1,Berner Klinik Montana,Impasse Palace Bellevue,1.0,3963,Crans-Montana,027/485.51.21,http://www.bernerklinik.ch,NaN,Rule_1,Rule_1,44,88
5,1,HVS - Hôpital de Sierre,Rue St-Charles,14.0,3960,Sierre,027/603.70.00,http://www.hopitalduvalais.ch,NaN,Rule_1,Rule_1,30,60

In [44]:
hospitals['ville'].unique()

array(['Monthey', 'St-Maurice', 'Martigny', 'Sion', 'Sierre',
       'Crans-Montana', 'Brig', 'Visp', 'Aigle', 'Vevey', 'Saxon',
       'Leukerbad', 'Montreuy'], dtype=object)

In [45]:
hospitalsModif=hospitals.loc[:,['ETABLISSEMENT','newBeds','ville']]
hospitalsModif.to_csv('hospitals_modif.csv',sep=',',encoding='utf-8')

In [46]:
for idx,row in hospitals.iterrows():
    print(row['ville'])
    print(idx)

Monthey
0
St-Maurice
1
Martigny
2
Sion
3
Sion
4
Sierre
5
Crans-Montana
6
Brig
7
Visp
8
Monthey
9
Aigle
10
Vevey
11
Sion
12
Saxon
13
Leukerbad
14
Crans-Montana
15
Crans-Montana
16
Sion
17
Vevey
18
Montreuy
19
Brig
20
Crans-Montana
21

In [47]:
groups=hospitals.groupby('ville')
groups.get_group('Brig')

,CLASSE,ETABLISSEMENT,Adresse,numero,npa,ville,telephone,site_internet,RuleID,RuleID_1,RuleID_2,beds,newBeds
7,1,HVS - Hôpital de Brigue,Oberlandstrasse,14.0,3900,Brig,027/604.33.33,http://www.spitalvs.ch/de/spital-wallis/stando...,NaN,Rule_1,Rule_1,45,90
20,1,HVS - Psychiatriezentrum Oberwallis,Oberlandstrasse,14.0,3900,Brig,027/604.33.33,http://www.hopitalvs.ch/de/unsere-fachbereiche...,NaN,Rule_1,Rule_1,42,84